//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sicse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coordinador
    {
        public int idCoordinador { get; set; }
        public int regional { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Regional Regional1 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
