//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sicse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipos()
        {
            this.Programacion = new HashSet<Programacion>();
        }
    
        public int idEquipos { get; set; }
        public string especificacion { get; set; }
        public string modelo { get; set; }
        public int Proyecto { get; set; }
        public int tipoEquipo { get; set; }
    
        public virtual Ascensores Ascensores { get; set; }
        public virtual Proyecto Proyecto1 { get; set; }
        public virtual TipoEquipo TipoEquipo1 { get; set; }
        public virtual Escaleras Escaleras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programacion> Programacion { get; set; }
    }
}
