//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sicse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formulario
    {
        public int idFormulario { get; set; }
        public string tipo { get; set; }
        public Nullable<int> idPlantillaFormulario { get; set; }
        public int Inspector { get; set; }
        public int Item { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Inspector Inspector1 { get; set; }
        public virtual Item Item1 { get; set; }
    }
}
