//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sicse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso
    {
        public int idIngreso { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public int Usuario { get; set; }
    
        public virtual Usuario Usuario1 { get; set; }
    }
}
