//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sicse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programacion
    {
        public int idProgramacion { get; set; }
        public Nullable<System.DateTime> fechaSolicitud { get; set; }
        public System.DateTime fechaProgramada { get; set; }
        public System.DateTime horaInicial { get; set; }
        public System.DateTime horaFinal { get; set; }
        public Nullable<int> numeroVisita { get; set; }
        public string area { get; set; }
        public string estado { get; set; }
        public int Proyecto { get; set; }
        public int Equipo { get; set; }
        public int Inspector { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Inspector Inspector1 { get; set; }
        public virtual Proyecto Proyecto1 { get; set; }
    }
}
