//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sicse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Ingreso = new HashSet<Ingreso>();
        }
    
        public int idUsuario { get; set; }
        public string nombres { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public string tipoDocumento { get; set; }
        public long documento { get; set; }
        public string correo { get; set; }
        public string clave { get; set; }
        public string estado { get; set; }
        public long telefono { get; set; }
        public Nullable<long> celular { get; set; }
        public int idRol { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        public virtual Coordinador Coordinador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingreso> Ingreso { get; set; }
        public virtual Inspector Inspector { get; set; }
        public virtual Rol Rol { get; set; }
        public virtual Zona Zona { get; set; }
    }
}
